export const CHANGE_CURRENCY_FIRST = 'CHANGE_CURRENCY_FIRST';
export const CHANGE_CURRENCY_SECOND = 'CHANGE_CURRENCY_SECOND';
export const CHANGE_CURRENCY_COURSE = 'CHANGE_CURRENCY_COURSE';
export const ADD_POSITION = 'ADD_POSITION';
export const DEL_POSITION = 'DEL_POSITION';
export const TOTAL_CURRENCY_FIRST_AND_SECOND = 'TOTAL_CURRENCY_FIRST_AND_SECOND';
export const CARD_PERSPECTIVE = 'CARD_PERSPECTIVE';
